# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields:
  username: theCapypara
  show_times: "true"
  show_ai_percentage: "true"
  stats:
    - dependencies
    - operating_systems
    - projects
    - machines
  display: items
  include_other: "false"

# override variables
variables:
  trmnl:
    is_trmnlp: true
